// Generated by CoffeeScript 1.6.3
(function() {
  var gulp, mocha;

  gulp = require('gulp');

  mocha = require('gulp-mocha');

  gulp.task('test', function() {
    return gulp.src(['test/*.js'], {
      read: false
    }).pipe(mocha({
      reporter: 'spec'
    }));
  });

  gulp.task('watch', function() {
    return gulp.watch(['src/**/*', 'test/**/*'], ['test']);
  });

  gulp.task('default', ['test']);

}).call(this);
