// Generated by CoffeeScript 1.6.3
(function() {
  var chai,
    __slice = [].slice;

  chai = require('chai');

  chai.use(function(chai, utils) {
    var Assertion;
    Assertion = chai.Assertion;
    Assertion.addMethod('transform', function() {
      var args, transform;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      transform = this._obj;
      return new Assertion(function() {
        return transform.apply(this, args);
      });
    });
    return Assertion.addMethod('into', function(expectedOutput) {
      var actualOutput;
      actualOutput = this._obj();
      return new Assertion(actualOutput).to.equal(expectedOutput);
    });
  });

}).call(this);
