// Generated by CoffeeScript 1.6.3
(function() {
  var compiler, jade;

  jade = require('jade');

  compiler = require('./compiler');

  module.exports = function(markup, options) {
    if (options == null) {
      options = {};
    }
    options.compiler = compiler;
    return jade.render(markup, options);
  };

}).call(this);
